### ISSUE TITLE
IoT Hub (without central) support timeline

### ISSUE THREAD

**Issue by oising** [codetunez/mock-devices#42]
I was super excited to see this project, but then I noticed that you only support working through IoT Central - but pure IoT hub is in your plans, it seems. What help would be needed to get this working directly with an IoT hub? I'm open to helping with a PR if there's a rough plan for what needs doing...

**Comment by francislatulippe** [comment]
I too see value in this

**Comment by codetunez** [comment]
Hi. So today you can use a connection string or DPS to create a device. Both of these options work with IoT Hub (directly). If there are other scenarios you are thinking please LMK

**Comment by oising** [comment]
Hi @codetunez - yes, we figured this out a few months ago. I'll close the issue.
